language: python
sudo: false
python:
  - '3.6'
install:
  - pip install -q python-coveralls
  - pip install -q -r requirements.txt
script:
  - pytest -v --tb=native --cov
after_success:
  - coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: patron3301
  password:
    secure: fgDlHJJX1jQRdQhrF+nnS3jI5hWJ6mi3ti3VKFN9n2eWp7BLH5cxv9F3ZR139+ROtyOGTeQz5oiO4tr7nI+IU2TriUxKYi1bH4rBrCVZPRN5uoN3PiBa+zE5TLYgV99Ycin4l9yePmRNbceo8Pg0BsEw3e0YENMclNXduzlVpxQS4qXb0ZDxIxo2RmVy4obAnLaHDZSVwpSLMQv49niiHBMuQuax4QzwwqeNpWBRReturJVNe/AvUhlziMrrJ09LqLZupNg4OHxvYJCrNEvHb0mlxe2KWkp2gA/RiVZ/0wRtAzBnHnogP8/dD8r7sCbtsh7DRfNVoMAfzN5D9sywwjNmU/7CDp1AelHJWIKPF5Mg29+5Xu3pzwN5dqeKLX0KmtQMv1hM7TEH5iT+BKl/3dAWBCmsWu3ldDwzksuUcreI4XO1enVaZlphIn5/cExrIEMNaaIV7zSVUJSjDGjnInuKPU4Sk8AVjscbcg4h6YJKhRWCTLgmAZRTck2WEQ1/I35lKUuS2KRI8oLih5eJISOjEv6bYLZz27GrgbSt0i0F7P5N9+uSlnuhI9zgM0v15rthkR+/DyUCtPcXz6p6H33GOAAt+STlkgLzDaAiFfIyBspUpJKSbZItxDxIsYrafnDvPjZxfa1Nr6wzjOdWpgJoKJjhjfKA3/b2Qs+wv04=
  on:
    tags: true
    repo: thesimj/envyaml
    python: '3.6'
