language: python
sudo: false
python:
  - '3.6'
install:
  - pip install -q python-coveralls
  - pip install -q -r requirements.txt
script:
  - pytest -v --tb=native --cov
after_success:
  - coveralls
deploy:
  provider: pypi
  user: patron3301
  password:
    secure: hUDkWKpBwG56BSW5GOezZVtT1s68LplrTEulSzGd9O3fAoYyU647n/azQ2SFqHWlyJd4gEHlMpMKFWEBgfK+lbOWdwhxJMnSFhaR50UdRfdW+K8lgk7IfiK4//7/dBzKGIVlSA1522KZTtTlrs0ejMBd38B+DpCUApTXH8OL4t9X4arygWcXSWZVb687BYr0MOgignGu/6oDURkQpkFxaUPKmgatNjrcOkHgz+PWCpEr6Fqeeki9iGCerjnYyNGLaJNviV/xuZeqQIMHXgf/mHF3QJoC+0Vfr4ITyHSJdQtJsXJA7vDeNs6AtdHo2w9VdqiB+95nMTJrsBG7PIAslvDlQyUYgqSJv4DvitnCf/YbuZrF3RNq1H9YH/XZOfTNPxm2+0adHlhHnqXPlAvdEPTSJKABrz736OZtpPBKNM84UtoEq83ytKLW3SNPob8F5s9V5PI/8eNQjz6dhxnI3m3f43GxYB+gL9NaWUe3GFpI8gS7pot0K6gB78Pp8sJF0b6493S26vK6T9yPZQOhcaCqyNNfzGULPr0+XyCongihPmjHT52ypH0WRW18Y2RHtl+bfD0RFbIBRXTi2krXhgeu9z0Clxg1vHYdeczjsbmc3/XWtfqM/38KrnxetQ0VHDAL47H3jUaXdMnxlC//0FSKjCtpBWxIzlFMCdqHPqw=
