language: python
sudo: false
python:
  - '3.6'
install:
  - pip install -q python-coveralls
  - pip install -q -r requirements.txt
script:
  - pytest -v --tb=native --cov
after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  on:
    python: '3.6'
    branch: master
    repo: thesimj/envyaml
